import js from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import importPlugin from 'eslint-plugin-import';
import sortKeysFix from 'eslint-plugin-sort-keys-fix';
import unusedImports from 'eslint-plugin-unused-imports';
import tseslint from 'typescript-eslint';

const eslintConfig = defineConfig([
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{js,ts,mjs,cjs}'],
    plugins: {
      import: importPlugin,
      'sort-keys-fix': sortKeysFix,
      'unused-imports': unusedImports,
    },
    rules: {
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-shadow': 'error',
      '@typescript-eslint/no-unused-expressions': ['error', { allowShortCircuit: true, allowTernary: true }],
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-use-before-define': ['error', { classes: true, functions: false, variables: true }],
      'array-bracket-spacing': ['error', 'never'],
      'arrow-body-style': ['error', 'as-needed'],
      'arrow-parens': ['error', 'always'],
      'arrow-spacing': ['error', { after: true, before: true }],
      'block-spacing': ['error', 'always'],
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      camelcase: ['error', { ignoreDestructuring: false, properties: 'never' }],
      'comma-dangle': ['error', {
        arrays: 'always-multiline',
        exports: 'always-multiline',
        functions: 'always-multiline',
        imports: 'always-multiline',
        objects: 'always-multiline',
      }],
      'comma-spacing': ['error', { after: true, before: false }],
      'comma-style': ['error', 'last'],
      'computed-property-spacing': ['error', 'never'],
      'constructor-super': 'error',
      curly: ['error', 'all'],
      'eol-last': ['error', 'always'],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'func-call-spacing': ['error', 'never'],
      'func-style': ['error', 'expression', { allowArrowFunctions: true }],
      'generator-star-spacing': ['error', { after: true, before: false }],
      'import/first': 'error',
      'import/newline-after-import': 'error',
      'import/no-duplicates': 'error',
      'import/no-webpack-loader-syntax': 'error',
      'import/order': ['error', {
        alphabetize: { caseInsensitive: true, order: 'asc' },
        groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'type'],
        'newlines-between': 'never',
      }],
      'import/prefer-default-export': 'off',
      'key-spacing': ['error', { afterColon: true, beforeColon: false }],
      'keyword-spacing': ['error', { after: true, before: true }],
      'linebreak-style': ['error', 'unix'],
      'lines-around-comment': 'off',
      'max-depth': ['warn', 4],
      'max-nested-callbacks': ['warn', 3],
      'max-params': 'off',
      'new-cap': ['error', {
        capIsNew: false,
        capIsNewExceptions: [],
        newIsCap: true,
        newIsCapExceptions: [],
      }],
      'new-parens': 'error',
      'no-alert': 'warn',
      'no-array-constructor': 'error',
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-class-assign': 'error',
      'no-confusing-arrow': ['error', { allowParens: true }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-const-assign': 'error',
      'no-continue': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-duplicate-imports': 'off',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-floating-decimal': 'error',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-mixed-operators': ['error', {
        allowSamePrecedence: false,
        groups: [
          ['%', '**'],
          ['%', '+'],
          ['%', '-'],
          ['%', '*'],
          ['%', '/'],
          ['/', '*'],
          ['&', '|', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!=='],
          ['&&', '||'],
        ],
      }],
      'no-mixed-spaces-and-tabs': 'error',
      'no-multi-spaces': ['error', { ignoreEOLComments: false }],
      'no-multi-str': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 0 }],
      'no-nested-ternary': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-object': 'error',
      'no-new-symbol': 'error',
      'no-new-wrappers': 'error',
      'no-param-reassign': ['error', { props: false }],
      'no-plusplus': 'off',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-restricted-globals': ['error', 'isFinite', 'isNaN'],
      'no-return-assign': ['error', 'always'],
      'no-return-await': 'error',
      'no-script-url': 'error',
      'no-self-assign': ['error', { props: true }],
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': 'off',
      'no-shadow-restricted-names': 'error',
      'no-tabs': 'error',
      'no-this-before-super': 'error',
      'no-throw-literal': 'error',
      'no-trailing-spaces': 'error',
      'no-undef': 'off',
      'no-undef-init': 'error',
      'no-undefined': 'off',
      'no-underscore-dangle': 'off',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'no-unused-expressions': 'off',
      'no-unused-vars': 'off',
      'no-use-before-define': 'off',
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-escape': 'error',
      'no-useless-rename': ['error', { ignoreDestructuring: false, ignoreExport: false, ignoreImport: false }],
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-whitespace-before-property': 'error',
      'no-with': 'error',
      'object-curly-newline': ['error', {
        ImportDeclaration: { consistent: false, multiline: false },
        ObjectExpression: { consistent: true, minProperties: 4, multiline: true },
        ObjectPattern: { consistent: true, minProperties: 4, multiline: true },
      }],
      'object-curly-spacing': ['error', 'always'],
      'object-shorthand': ['error', 'always', { avoidQuotes: true, ignoreConstructors: false }],
      'one-var': ['error', 'never'],
      'one-var-declaration-per-line': ['error', 'always'],
      'operator-assignment': ['error', 'always'],
      'operator-linebreak': ['error', 'before', { overrides: { '=': 'none' } }],
      'padded-blocks': ['error', 'never'],
      'prefer-arrow-callback': ['error', { allowNamedFunctions: false, allowUnboundThis: true }],
      'prefer-const': 'error',
      'prefer-destructuring': ['error', {
        AssignmentExpression: { array: true, object: false },
        VariableDeclarator: { array: false, object: true },
      }, { enforceForRenamedProperties: false }],
      'prefer-numeric-literals': 'error',
      'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'quote-props': ['error', 'as-needed', { keywords: false, numbers: false, unnecessary: true }],
      quotes: ['error', 'single', { allowTemplateLiterals: false, avoidEscape: true }],
      radix: 'error',
      'require-yield': 'error',
      'rest-spread-spacing': ['error', 'never'],
      semi: ['error', 'always'],
      'semi-spacing': ['error', { after: true, before: false }],
      'sort-imports': ['error', {
        ignoreCase: true,
        ignoreDeclarationSort: true,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
      }],
      'sort-keys': 'off',
      'sort-keys-fix/sort-keys-fix': ['error', 'asc', { caseSensitive: false, natural: true }],
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', {
        anonymous: 'always',
        asyncArrow: 'always',
        named: 'never',
      }],
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-unary-ops': ['error', { nonwords: false, words: true }],
      'spaced-comment': ['error', 'always', {
        block: { balanced: true, exceptions: ['-', '+'], markers: ['=', '!', ':', '::'] },
        line: { exceptions: ['-', '+'], markers: ['=', '!', '/'] },
      }],
      'symbol-description': 'error',
      'template-curly-spacing': 'error',
      'template-tag-spacing': ['error', 'never'],
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': ['warn', {
        args: 'after-used',
        argsIgnorePattern: '^_',
        vars: 'all',
        varsIgnorePattern: '^_',
      }],
      'vars-on-top': 'error',
      'wrap-iife': ['error', 'outside', { functionPrototypeMethods: false }],
      'yield-star-spacing': ['error', 'after'],
      yoda: 'error',
    },
  },
  globalIgnores([
    'dist/**',
    'node_modules/**',
  ]),
]);

export default eslintConfig;
